### ISSUE TITLE
Errors in CLI but works

### ISSUE THREAD

**Issue by c1tyguide** [tjclement/nukedns#1]
Running on router with 3299k denylist.txt

> /tmp/bin # ./nukedns &
> /tmp/bin # thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Timeout }', src/main.rs:35:74
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Timeout }', src/main.rs:35:74
> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Timeout }', src/main.rs:35:74
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
> thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:95:65
>

**Comment by shanx** [comment]
hey @c1tyguide very nice to see that you're using nukedns, for us this was a way of learning more about rust. I don't think we will have time to look into this issue unfortunately. Just to set expectations :)

**Comment by tjclement** [comment]
Looks like there was a timeout querying an upstream DNS server, and we don't handle any errors there. If you'd like to use this project without any code changes, you could consider naively restarting the process when it exits. If you're up for making changes, getting rid of the `.unwrap()` calls is the proper way of fixing this issue from happening (thanks https://github.com/Trangar/ for the pointer).
